[package]
name = "gbos-rust-part"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.9.8"

[build-dependencies]
bindgen = "0.70.1"

[profile.dev]
panic = "abort"

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package."gbos-rust-part"]
opt-level = 1

[profile.dev.build-override]
opt-level = 0
codegen-units = 256
debug = false

[profile.release.build-override]
opt-level = 0
codegen-units = 256
debug = false
