[build]
target = 'x86_64-unknown-none.json'
# target = "riscv64gc-unknown-none-elf"
target-dir = 'build'

[unstable]
build-std-features = ['compiler-builtins-mem']
build-std = ['core', 'compiler_builtins', 'alloc']
