[package]
name = "eonix_sync"
version = "0.1.0"
edition = "2024"

[dependencies]
arch = { path = "../../arch" }
eonix_preempt = { path = "../eonix_preempt" }

[features]
default = []
no_check_locked = []
