name: Test Build

on:
  push:
    branches-ignore:
      - comp-and-judge
  pull_request:
    branches-ignore:
      - comp-and-judge
  workflow_dispatch:

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup rust nightly
        run: rustup component add rust-src llvm-tools

      - name: Configure
        run: ./configure

      - name: Build for riscv64 targets
        run: make build ARCH=riscv64 MODE=release

      - name: Upload riscv64 build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-riscv64
          path: build/riscv64gc-unknown-none-elf/release/eonix_kernel

      - name: Build for loongarch64 targets
        run: make build ARCH=loongarch64 MODE=release

      - name: Upload loongarch64 build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-loongarch64
          path: build/loongarch64gc-unknown-none-elf/release/eonix_kernel
